@startuml devtools
actor user
control onLoad
boundary Application
entity Grudges

onLoad -> Application : render
Application -> Application : <Grudges \ntitle=Unavenged Grudges \ngrudges={unavengedgrudges} \nonCheckOff={this.toggle} \nonRemove={this.removeGrudge} \n/>  /> 
user -> Application : click checkbox
Application -> Grudges : click checkbox
Grudges -> Grudges : 
@enduml